<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Item_1</name>
   <tag></tag>
   <elementGuidId>a2e0393d-7671-40c7-be2b-9d716198323d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tpz-med-fnt3.agr-sublist-list.agr-cursor-pointer.agr-front-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a6d1b60-4816-4265-91ce-ff62ae222aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-node</name>
      <type>Main</type>
      <value>060101</value>
      <webElementGuid>3bc72adf-be96-440e-b92d-8d3e19024e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/item</value>
      <webElementGuid>a60edd46-27ef-4127-a165-59f54d0e2b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu</value>
      <webElementGuid>07c39c27-4e8b-4ddd-8743-d701d10be70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Item
                                        </value>
      <webElementGuid>8926eb18-4882-4bcd-857f-e438981de4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agr_master_page&quot;)/div[@class=&quot;agr-sub-masterpage&quot;]/div[@class=&quot;agr-margin-top-30&quot;]/div[@class=&quot;agr-dashboard-sublist-container&quot;]/div[@class=&quot;row agr-destroy-margin&quot;]/div[@class=&quot;col-lg-4 agr-child-page agr-sublist agr-margin-bottom-15 agr-destroy-padding&quot;]/div[@class=&quot;agr-card-style agr-padding-all-10&quot;]/div[2]/div[@class=&quot;tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu&quot;]</value>
      <webElementGuid>8cb0b605-eefe-4501-ae94-29b51ea4353b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>91380d42-564c-4809-8ebd-f3a2770bfdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration'])[3]/following::div[2]</value>
      <webElementGuid>590db607-b972-4367-87ea-58947b9fea61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHILD PAGES'])[1]/following::div[8]</value>
      <webElementGuid>1c18fc32-7fba-4021-9c63-b5046112529e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Family'])[3]/preceding::div[1]</value>
      <webElementGuid>1dc70570-a088-4a04-a191-e1614586e7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store Inventory'])[3]/preceding::div[2]</value>
      <webElementGuid>c76139f4-a059-4819-ab79-d1fe85cd3507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>9c4f49e3-12c8-4d8c-bd20-26e41e7b99fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            Item
                                        ' or . = '
                                            Item
                                        ')]</value>
      <webElementGuid>d312c8bd-f7e5-49e6-af3c-4249235c36ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
