<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0000000002 - DKSH HOLDINGS (MALAYSIA) B_e3a5f9</name>
   <tag></tag>
   <elementGuidId>5bc7e07a-2301-4c7b-b93c-43fbb58fe17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-59']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-59</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97976b88-b9ef-414f-a5e7-6931198da26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-pri-fnt2 ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>489733ce-26a4-4d14-9e30-df46d048d7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-59</value>
      <webElementGuid>51a1bb31-12d9-43fa-bc13-d12b2e7a1593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2105a25b-9cb1-4875-a85b-168a9773525b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0000000002 - DKSH HOLDINGS (MALAYSIA) BERHAD (231378-A)</value>
      <webElementGuid>6e8e10fa-4b1f-4980-b2a4-220aac2d9851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-59&quot;)</value>
      <webElementGuid>512ce044-928b-42b0-853d-e92722e822a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-59']</value>
      <webElementGuid>21d57185-1cb0-45d6-a662-977d0876fb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-56']/li/div</value>
      <webElementGuid>0e0ec89e-ddf0-4a13-9a35-647665bb0942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-59', '&quot;', ')')])[1]/following::div[14]</value>
      <webElementGuid>7a4cb547-284e-4ce6-90db-335bee689065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DKSH HOLDINGS (MALAYSIA) BERHAD (231378-A)'])[1]/preceding::div[60]</value>
      <webElementGuid>da16a849-0db3-4dd5-947c-e21a2610ed9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0000000002 - DKSH HOLDINGS (MALAYSIA) BERHAD (231378-A)']/parent::*</value>
      <webElementGuid>78ab7183-6c35-4750-98cb-aa9a24d82f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[13]/li/div</value>
      <webElementGuid>7a677ef9-15af-49f4-8107-eaee11820596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-59' and (text() = '0000000002 - DKSH HOLDINGS (MALAYSIA) BERHAD (231378-A)' or . = '0000000002 - DKSH HOLDINGS (MALAYSIA) BERHAD (231378-A)')]</value>
      <webElementGuid>1041058d-fdf6-4220-bf2b-af996aba358b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
