<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Item</name>
   <tag></tag>
   <elementGuidId>40909fc0-14ea-4852-a53d-e493b78033c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tpz-med-fnt3.agr-sublist-list.agr-cursor-pointer.agr-front-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdc35271-5e2c-4458-9d76-2ba45eb7fe56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-node</name>
      <type>Main</type>
      <value>060101</value>
      <webElementGuid>5bd35ca2-c365-4ce0-9a92-b4d4598591f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/item</value>
      <webElementGuid>01f140cb-a48c-429d-acdf-585e5d2c8763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu</value>
      <webElementGuid>2d1e7a64-21af-44dd-add3-5c8d6fb09228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Item
                                        </value>
      <webElementGuid>50fe9b3b-3711-493b-9f63-e2e55fee91e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agr_master_page&quot;)/div[@class=&quot;agr-sub-masterpage&quot;]/div[@class=&quot;agr-margin-top-30&quot;]/div[@class=&quot;agr-dashboard-sublist-container&quot;]/div[@class=&quot;row agr-destroy-margin&quot;]/div[@class=&quot;col-lg-4 agr-child-page agr-sublist agr-margin-bottom-15 agr-destroy-padding&quot;]/div[@class=&quot;agr-card-style agr-padding-all-10&quot;]/div[2]/div[@class=&quot;tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu&quot;]</value>
      <webElementGuid>adfcb324-4fa1-4ec5-bc6a-b46ae6437abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>2c41c874-e0b5-43f4-b2a2-1cd43ab047e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration'])[3]/following::div[2]</value>
      <webElementGuid>053a6875-6ef2-454c-be25-2cc604587c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHILD PAGES'])[1]/following::div[8]</value>
      <webElementGuid>b29d86fc-2d12-4243-ae95-88c95536b20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Family'])[3]/preceding::div[1]</value>
      <webElementGuid>20e61e06-71d7-49b9-94cb-1fdc84db45bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store Inventory'])[4]/preceding::div[2]</value>
      <webElementGuid>c56ded61-a118-4d65-a6cd-30a16dd9fafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>0c2e2084-8779-4495-aa4b-fa153ecb9756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            Item
                                        ' or . = '
                                            Item
                                        ')]</value>
      <webElementGuid>049e42fc-19a6-46fb-baf5-1bc2113eac6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
