<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Member Price_setStandardSellPrice</name>
   <tag></tag>
   <elementGuidId>4efe8cb6-1624-4867-b84a-50a38b913c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='set_standard_sell_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#set_standard_sell_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>455ff907-a7d8-4d5b-8988-2317938edc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88894b32-1a7e-4d96-ae3d-9bc49f6b8b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>set_standard_sell_price</value>
      <webElementGuid>69c7fc40-afb0-4ab1-a2cb-7e16820e736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setStandardSellPrice</value>
      <webElementGuid>a8916206-c72f-49cf-9be5-fe45de0c05bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a31dcbb-8841-4f24-bc40-4f36e8a4fdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>c91b3e52-07bf-4aaf-a811-199492decf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>-99999999.99</value>
      <webElementGuid>c64a8233-37ee-4d74-9f3a-dd79da30da08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>a8da57a5-7be8-4b67-9ecc-283eea1c00f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-text-right standard-sell-price agr-form-input agr-display-inline agr-width-hundred</value>
      <webElementGuid>50223fb4-c4c2-4da8-b71d-cd9a86327e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8b6313a-33e7-4b70-a94e-a17e88577293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9cba6a4d-ea93-44bf-8515-ec0c3d5d3645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>5b69f763-407c-4aa4-9626-bffb78641238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digits</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4aacdb7a-eeea-49ba-a4cd-055e7129de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e30ebc4-7467-43fd-82bf-ab636dce439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-error</name>
      <type>Main</type>
      <value>Member Price cannot be lesser than {1}.</value>
      <webElementGuid>f5abc07f-0b01-4ecd-82df-4136105e89e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max-error</name>
      <type>Main</type>
      <value>Member Price cannot be greater than {1}.</value>
      <webElementGuid>780569c9-8a2b-470d-b534-bcb75ae6abca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59998e3f-1ec8-4ce1-8590-a20a9a393782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;set_standard_sell_price&quot;)</value>
      <webElementGuid>37d59109-5967-49f0-92a0-0ebfbbeae80e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='set_standard_sell_price']</value>
      <webElementGuid>201c02cb-52cf-4735-aa41-dbed7a9cfdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general']/div[2]/div[2]/div/input</value>
      <webElementGuid>86410490-203a-48df-8b8f-b3893798bf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>74af1591-0b17-437c-9a62-927aa79104e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'set_standard_sell_price' and @name = 'setStandardSellPrice']</value>
      <webElementGuid>cc56f82e-0e60-4928-adc5-237d38b0941b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
