<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recommended Selling Price_setMarketSellPrice</name>
   <tag></tag>
   <elementGuidId>86e92285-4e16-405d-80b6-deea1e399a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='set_market_sell_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#set_market_sell_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0607f46-88e5-43f8-8cec-0e478854966b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69ac0d13-e1e8-43f3-907f-dc4fce3eeedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>set_market_sell_price</value>
      <webElementGuid>08b85004-4c6b-4fa7-a326-a54da85802f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setMarketSellPrice</value>
      <webElementGuid>22ca8ef4-90c5-46a2-a815-8801c847973d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b07efabb-de04-4cba-a65a-3784ac2915b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>3c6bff3e-5c5d-4571-a3db-d9c910fad8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>-99999999.99</value>
      <webElementGuid>0f1b40ea-0068-4f46-a294-a9755ca16823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>f57bc748-0c2f-473b-9177-f51981f92300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-text-right market-sell-price agr-form-input agr-display-inline agr-width-hundred</value>
      <webElementGuid>17d2f154-d64e-46b1-b60f-a943e4a261e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd8c016e-eafc-461b-a907-1f723ba8fd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bfb077c1-9ea8-4035-a0d0-96cdfb29d2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>317d950e-3376-46e7-87da-fd0f54562a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digits</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>890199c5-9077-40d1-8425-979219b85e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c15cd8a6-f036-4a4f-9a45-3284399b0b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-error</name>
      <type>Main</type>
      <value>Recommended Selling Price cannot be lesser than {1}.</value>
      <webElementGuid>34b165f5-74e9-4e11-81be-3112d64983d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max-error</name>
      <type>Main</type>
      <value>Recommended Selling Price cannot be greater than {1}.</value>
      <webElementGuid>a27876e8-0025-4946-920a-6753f6ff333e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85090afe-e6c6-4523-afdb-f0b3ab997fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;set_market_sell_price&quot;)</value>
      <webElementGuid>5e6db032-1ad4-4a01-832c-adcd489be3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='set_market_sell_price']</value>
      <webElementGuid>054c19b7-5df7-4160-89cf-c9e2f93c7618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general']/div[2]/div/div/input</value>
      <webElementGuid>56ca63b4-8f73-4736-b145-4ea09730cf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>8c2baf66-1a8e-4436-8914-442097a397a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'set_market_sell_price' and @name = 'setMarketSellPrice']</value>
      <webElementGuid>e2c8a10c-1e88-4290-9204-7c32009f315f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
