<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Cost Excl. Tax_itemSupplierForm._785183</name>
   <tag></tag>
   <elementGuidId>66616ccb-a5ff-4b4c-b3ca-1d9794b7851a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supplier_standard_unit_cost_excl_vat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#supplier_standard_unit_cost_excl_vat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4268d1f-ac4b-4f07-874b-2f9604573fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00575064-f41d-46b6-9546-758008a941a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supplier_standard_unit_cost_excl_vat</value>
      <webElementGuid>293b6658-1d56-4406-9bf0-9283c0f5e363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemSupplierForm.standartUnitCostExclVAT</value>
      <webElementGuid>0766ce3e-c9ef-4f3e-a82a-700aa0cde288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5ea9251e-56d3-4c2e-a8db-5fef0bbd6197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>efe4d64c-c2bc-450c-b0e1-78fab20d2e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5c02de9-4517-47c4-ae55-453dc5418348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>7702bf92-614b-47d9-95da-40a9939c8534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-form-input agr-display-inline agr-width-hundred</value>
      <webElementGuid>67f1b1b7-75b6-4bc4-95b5-54a777df2268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>0817e090-735d-47e0-9ee5-8843b329d631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cafeb8a3-cba4-4b00-9494-7b77c25d61e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>f94d79b2-9f1b-47c2-bc46-96179b139de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>640a2a6d-1988-4096-94a2-919226d93eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digits</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ca215d67-48c2-4fdb-af6d-3eeade7f0cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ccc0dc1-f34d-4ee7-b1c7-eb9633a30326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-error</name>
      <type>Main</type>
      <value>Unit Cost Excl. Tax cannot be lesser than {1}.</value>
      <webElementGuid>61c9e7b2-c537-4e35-b2f1-a9a5843bcf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max-error</name>
      <type>Main</type>
      <value>Unit Cost Excl. Tax cannot be greater than {1}.</value>
      <webElementGuid>08e3c06b-d1fb-4a3f-9022-9f99a8df3851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier_standard_unit_cost_excl_vat&quot;)</value>
      <webElementGuid>4e7be41a-2078-40a9-abd0-371964f42535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supplier_standard_unit_cost_excl_vat']</value>
      <webElementGuid>9a8960de-0b70-47bd-b20b-1669332ee01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_supplier_form']/div[5]/div[3]/div/input</value>
      <webElementGuid>85ac2cdb-18b0-4223-bd29-bf584b85689c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/input</value>
      <webElementGuid>4e40ce2d-5cd7-4ce0-ae4f-1bbbce8cedd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'supplier_standard_unit_cost_excl_vat' and @name = 'itemSupplierForm.standartUnitCostExclVAT' and @placeholder = 'Mandatory']</value>
      <webElementGuid>21d2d15f-50b2-4254-b1fe-afb034791399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
