<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Package Weight_itemFeatureForm.packageWeight</name>
   <tag></tag>
   <elementGuidId>d742f080-2b3c-4337-a139-926599d0c207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='package_weight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#package_weight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18655070-fe56-4c9c-955e-95cf216b6b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab49b5c1-5967-43a5-b5c1-8c8e08d7a0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>package_weight</value>
      <webElementGuid>c0d197d3-d6fc-4975-8afc-1b9316c6950b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemFeatureForm.packageWeight</value>
      <webElementGuid>64487b70-f0d6-495f-b29f-bd224ea4d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>410196ff-a152-4c94-bdbb-7013d10ef1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c04a1612-38d0-4dd2-8744-4f0df9a37ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0.0001</value>
      <webElementGuid>850fddad-39f6-47e9-a984-3686c7115e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>999999999.9999</value>
      <webElementGuid>d3180c76-f212-42f2-a75d-c8e9e295ce5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-form-input agr-display-inline agr-width-hundred mandatory</value>
      <webElementGuid>729a6748-2ef9-4370-a65d-e833278161e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Weight (kg)</value>
      <webElementGuid>fc6e9506-a357-4ae3-9946-0ed069b04255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e3452c0d-9a83-4e39-b4e6-b1bb526bf6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>6e118c8e-f65c-4e0c-855d-0c26b698f29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digits</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>285e4628-ff9b-4ca8-bd9c-f6f086ba352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5639a884-ce49-4f83-a26f-bbb0d79da67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-error</name>
      <type>Main</type>
      <value>Weight (kg) cannot be lesser than {1}.</value>
      <webElementGuid>5ba24a14-8b09-4929-9db8-a8617b090880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max-error</name>
      <type>Main</type>
      <value>Weight (kg) cannot be greater than {1}.</value>
      <webElementGuid>41b6e61d-2939-4917-a84b-5a5e28305f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0.0001</value>
      <webElementGuid>e0d6d92f-f128-4fed-bfd1-ef7cdea0eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;package_weight&quot;)</value>
      <webElementGuid>85d8b52b-2552-4747-a254-7e6d92ea1d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='package_weight']</value>
      <webElementGuid>44b3ed18-db73-4344-97fd-619a317110f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section5']/div[3]/div/div/input</value>
      <webElementGuid>27531cb3-23eb-4213-9f85-b4c651459d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[10]/div[3]/div/div/input</value>
      <webElementGuid>4f56e543-eb73-44a8-9148-224590ebb909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'package_weight' and @name = 'itemFeatureForm.packageWeight' and @placeholder = 'Weight (kg)']</value>
      <webElementGuid>be8fbfe5-db32-4108-ac26-20daa9b59db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
