<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MandatoryBy AIR (if urgent)By OCEAN _c0219a</name>
   <tag></tag>
   <elementGuidId>3b1aed5e-dd85-4856-aac2-593264b75811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='item_analysis_feature4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_analysis_feature4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db2b416b-5f1a-4b97-b96a-7768ffcf369c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_analysis_feature4</value>
      <webElementGuid>1ef4a1eb-95d4-4489-b4b1-03b016ad07d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAnalysisForm.feature4</value>
      <webElementGuid>8c4b04d4-e51f-4d0d-b583-bb5ddcdabae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>cebee949-ea30-4aaa-8df7-cc5c2cdc980e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8b6b8dd8-9216-46ff-891a-70a29e8c05fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>443cc1eb-b834-4725-b453-dba49b45cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MandatoryBy AIR (if urgent)By OCEAN (if urgent)</value>
      <webElementGuid>71d7c86b-fd2c-4502-8d6a-983eec1c0f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_analysis_feature4&quot;)</value>
      <webElementGuid>c74d3d36-8130-4686-8a34-1e9e3d2d2fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='item_analysis_feature4']</value>
      <webElementGuid>3ceda108-9be7-4a0f-8dc2-dcf62c29df58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[5]/div[4]/div/select</value>
      <webElementGuid>4771f7aa-5a65-4380-9064-d7527da100bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Urgent Shipping Mode (EM)'])[1]/following::select[1]</value>
      <webElementGuid>a3c54f4b-f641-4b83-afd3-b376b0164657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Standard Shipping Mode (EM)'])[1]/following::select[2]</value>
      <webElementGuid>b9c0efe6-ebfb-4d6a-9eb0-bd1b873e0f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Control Item'])[1]/preceding::select[1]</value>
      <webElementGuid>591408ba-8a13-4856-9df5-fb0e1f538779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retention Day'])[1]/preceding::select[2]</value>
      <webElementGuid>6d9a0041-3748-4756-8de1-4dc911edabc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div/select</value>
      <webElementGuid>98eb5c2e-6070-4afe-9473-20bc371e2108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'item_analysis_feature4' and @name = 'itemAnalysisForm.feature4' and (text() = 'MandatoryBy AIR (if urgent)By OCEAN (if urgent)' or . = 'MandatoryBy AIR (if urgent)By OCEAN (if urgent)')]</value>
      <webElementGuid>b1e2a747-8112-4350-98a0-d21d5e7835d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
