<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PREMIUMEXCLUSIVENO INCENTIVE</name>
   <tag></tag>
   <elementGuidId>45ef403f-20a5-4faf-aa07-fe0b4b492296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='incentive_model']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#incentive_model</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>701d6b47-323b-40be-ae74-81da88ed8b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incentive_model</value>
      <webElementGuid>a0e949bf-9513-4753-bf2c-fc6789acca9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAttributeForm.kads1mFlag</value>
      <webElementGuid>b7592e6c-7756-4900-9de6-a434703b8944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred</value>
      <webElementGuid>741e2d02-75c0-4b56-a96e-ded25fedc64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f588dc5a-265d-49c7-baa3-a4ad937cfc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7e06097b-bf45-4814-827c-8f350b792ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PREMIUMEXCLUSIVENO INCENTIVE</value>
      <webElementGuid>7ae1d905-b0e6-44db-8b11-efe10da687a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incentive_model&quot;)</value>
      <webElementGuid>41a4c918-bdc9-4489-b260-738d5c499e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='incentive_model']</value>
      <webElementGuid>aab4354f-57be-4e59-98e0-bf1303b4c911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[5]/div[2]/div/select</value>
      <webElementGuid>4c7a3727-99e3-4401-afcb-ed65539dc23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incentive Model'])[2]/following::select[1]</value>
      <webElementGuid>033717a9-9b21-457e-91da-995945b5d39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::select[2]</value>
      <webElementGuid>4c611269-9a4c-4e71-a132-3c3eaf129c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Standard Shipping Mode (EM)'])[1]/preceding::select[1]</value>
      <webElementGuid>700ca342-b821-4237-8028-88c45533da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Urgent Shipping Mode (EM)'])[1]/preceding::select[2]</value>
      <webElementGuid>1bffe95e-61ad-477d-a137-ea970c315965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>065693a1-9095-4ce5-8cec-5d1824d47d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'incentive_model' and @name = 'itemAttributeForm.kads1mFlag' and (text() = 'PREMIUMEXCLUSIVENO INCENTIVE' or . = 'PREMIUMEXCLUSIVENO INCENTIVE')]</value>
      <webElementGuid>a2e3fc21-e7c0-45b7-b839-c9deddb2d622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
