<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MandatoryBy AIR (Standard)By OCEAN (_50da7d</name>
   <tag></tag>
   <elementGuidId>17041149-b649-477f-bb12-06152b428b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='item_analysis_feature3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_analysis_feature3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4beec3bd-2c7c-4d3c-b7f7-3fcc8abca297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_analysis_feature3</value>
      <webElementGuid>5fe67767-a2e1-4084-a8a9-85641c4a42c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAnalysisForm.feature3</value>
      <webElementGuid>279a2898-8ee5-4666-9597-3492faddc08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>c15fe7ca-21a5-4da1-906d-20709aabd0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>099662ff-5303-43c8-bfe5-f9761258daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12209813-2234-4615-8d43-1c04655aaf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MandatoryBy AIR (Standard)By OCEAN (Standard)</value>
      <webElementGuid>44aff64f-15d6-441f-ada3-f64e8e91e633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_analysis_feature3&quot;)</value>
      <webElementGuid>0b82bc71-4976-4c9b-9728-2f6bc8fcfa94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='item_analysis_feature3']</value>
      <webElementGuid>54cf071c-912e-4528-a39c-8e48a42c7743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[5]/div[3]/div/select</value>
      <webElementGuid>cf661b84-45ac-4382-909f-182b793979c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Standard Shipping Mode (EM)'])[1]/following::select[1]</value>
      <webElementGuid>3702cd31-b873-49f1-bdb6-ba58d3ab2b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incentive Model'])[2]/following::select[2]</value>
      <webElementGuid>b7553306-aaab-4aaf-9290-a3d2c8825f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Urgent Shipping Mode (EM)'])[1]/preceding::select[1]</value>
      <webElementGuid>f74f3d61-1983-4e31-8d11-8b172187c112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Control Item'])[1]/preceding::select[2]</value>
      <webElementGuid>e942855e-ad8b-4acc-ad86-98142b3c42ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/select</value>
      <webElementGuid>3d6e193f-960a-4bd9-9071-a61bec80de06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'item_analysis_feature3' and @name = 'itemAnalysisForm.feature3' and (text() = 'MandatoryBy AIR (Standard)By OCEAN (Standard)' or . = 'MandatoryBy AIR (Standard)By OCEAN (Standard)')]</value>
      <webElementGuid>c905d76a-571c-457a-90ce-1990c188e05c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
