<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mandatory1M2M3M4M5M6M7M8M9M10M12MEXNANR</name>
   <tag></tag>
   <elementGuidId>1b1c628f-1c25-48fd-93fa-08929ed0296a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='return_policy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return_policy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6bf6bcc3-778b-416e-9730-f097f2bfb318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>return_policy</value>
      <webElementGuid>295f3796-f947-4083-81a2-8753c263f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAttributeForm.returnPolicy</value>
      <webElementGuid>f68cefc0-91ea-407a-91c0-6f354ecb7bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>ea1a35c3-450c-4ea9-83f2-f8af2e368905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3107935-ec67-490e-9517-d695dfd82d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>98cfe703-2c72-47c8-a5f0-4cc68d54564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mandatory1M2M3M4M5M6M7M8M9M10M12MEXNANR</value>
      <webElementGuid>a2b1ba31-a3f0-4959-9c76-3a420b3c8adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return_policy&quot;)</value>
      <webElementGuid>d49504f7-cc4c-4989-a7d6-db78005b3621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='return_policy']</value>
      <webElementGuid>b71a0939-9870-491a-9c60-839b1574b848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[8]/div[2]/div/select</value>
      <webElementGuid>bb209683-cc00-4455-9488-af795e61e61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Policy'])[1]/following::select[1]</value>
      <webElementGuid>5c7ea924-13ad-4839-92d4-a0ae494547c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[13]/following::select[1]</value>
      <webElementGuid>0be98499-094c-4f42-8f35-c47f7a16321f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature'])[1]/preceding::select[1]</value>
      <webElementGuid>8def7170-cc3c-4cef-abdb-5e05ca976a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Order (Warehouse)'])[1]/preceding::select[2]</value>
      <webElementGuid>bc6f46c8-8db1-4703-8f0c-2e70c020d3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/select</value>
      <webElementGuid>f3396def-c7c5-409c-b8bb-26a4eda0f456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'return_policy' and @name = 'itemAttributeForm.returnPolicy' and (text() = 'Mandatory1M2M3M4M5M6M7M8M9M10M12MEXNANR' or . = 'Mandatory1M2M3M4M5M6M7M8M9M10M12MEXNANR')]</value>
      <webElementGuid>83bbf710-8b9e-4059-b043-def809555135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
