<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MandatoryHQ Main WHHQ Sub WHSub WH O_9c4e63</name>
   <tag></tag>
   <elementGuidId>d5240de8-e202-40bc-a0a1-14aff8b2c43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='warehouse_item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#warehouse_item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48f1bad9-7d55-48f9-b911-03a5b3448abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warehouse_item</value>
      <webElementGuid>8c825d5a-de7f-4f48-a96a-8766bd2f0a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAttributeForm.warehouseItem</value>
      <webElementGuid>ebd7e6e8-e11a-4872-8a81-1a663f631a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>f0a47405-ff3b-4ef6-9d6d-e3898cea4bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bce9160b-de8a-47ce-9b00-ea4a4f7bc777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c4c55bc-e39e-46ee-8e29-24d0f1e638f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MandatoryHQ Main WHHQ Sub WHSub WH OrderStore/HQ Order</value>
      <webElementGuid>fb86d02a-e964-4bbc-b2d2-24b8e02af8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warehouse_item&quot;)</value>
      <webElementGuid>c5dc721b-fe6b-41dd-983e-4241413214d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='warehouse_item']</value>
      <webElementGuid>ca44f9b2-7dee-47b8-b17f-40520c8746fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[5]/div/div/select</value>
      <webElementGuid>a0581910-850e-4968-ad19-9e5c29038fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::select[1]</value>
      <webElementGuid>021099be-d699-47e1-a70d-cb387a97b736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Model'])[2]/following::select[1]</value>
      <webElementGuid>2fe983cb-2db1-4976-af9e-8d619d401683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incentive Model'])[2]/preceding::select[1]</value>
      <webElementGuid>8099038b-dbbe-4e23-b7e2-6dd9d610a0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Standard Shipping Mode (EM)'])[1]/preceding::select[2]</value>
      <webElementGuid>bcb12b2f-c9dd-45bc-a978-eae7111764d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>91da03d2-13a1-4870-83e0-3388e7e73c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'warehouse_item' and @name = 'itemAttributeForm.warehouseItem' and (text() = 'MandatoryHQ Main WHHQ Sub WHSub WH OrderStore/HQ Order' or . = 'MandatoryHQ Main WHHQ Sub WHSub WH OrderStore/HQ Order')]</value>
      <webElementGuid>c123ca01-6de0-4237-aa5d-67ce70770206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
