<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MandatoryNo ControlBatch and Expiry _c38986</name>
   <tag></tag>
   <elementGuidId>8ce21a50-dfe0-45ce-8763-0bcd459e231b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='batch_control_item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#batch_control_item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>888fd567-6ee5-4270-b885-c4de20a1179c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>batch_control_item</value>
      <webElementGuid>ee858b87-7634-4ed8-b091-abf9f894fc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemAttributeForm.batchControl</value>
      <webElementGuid>8eeb1d0b-4501-4e2f-b677-a23d5ee26f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>496ba7e1-a518-4998-937f-e31fb13ef573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>404683bb-c5ab-4b38-ae02-feb5ad274368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a770ba96-6d8a-4cdc-84b4-ea45e133e4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MandatoryNo ControlBatch and Expiry Date (DC)</value>
      <webElementGuid>cf790dcf-5625-4f92-a1f5-09e7f5117653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batch_control_item&quot;)</value>
      <webElementGuid>f55d160d-08e7-4fcf-a571-f60c4f4a9e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='batch_control_item']</value>
      <webElementGuid>08f37bd9-478b-400f-9bd9-bb793a94fd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section3']/div[6]/div/div/select</value>
      <webElementGuid>bf89a5a2-7144-4b03-86f6-35e56f5c281b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Control Item'])[1]/following::select[1]</value>
      <webElementGuid>0ed16c53-22c2-4a77-aeeb-ae0d59c14926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oversea Urgent Shipping Mode (EM)'])[1]/following::select[2]</value>
      <webElementGuid>57bcc7da-3b55-4619-8049-d36805639cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retention Day'])[1]/preceding::select[1]</value>
      <webElementGuid>439ea8bc-860b-4396-819d-268b5d1f6835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print QR Code'])[3]/preceding::select[1]</value>
      <webElementGuid>1e270537-8381-4e41-a0b3-78fd628c22f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/select</value>
      <webElementGuid>f7b0fafb-7108-4f5c-8fc1-179874ef3962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'batch_control_item' and @name = 'itemAttributeForm.batchControl' and (text() = 'MandatoryNo ControlBatch and Expiry Date (DC)' or . = 'MandatoryNo ControlBatch and Expiry Date (DC)')]</value>
      <webElementGuid>66fc08bd-aec3-48e2-97bb-d20a2de30ab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
