<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MandatoryGeneralWeighingVariantsPost_d44cf2</name>
   <tag></tag>
   <elementGuidId>1ad48753-ee59-4e0f-9207-59767aacda8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='merchandise_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#merchandise_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>831702c4-9a9f-4875-8de6-4b8a317f3909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merchandise_type</value>
      <webElementGuid>0314d1de-9755-4f6d-994a-aa583c950e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemBomForm.merchandiseType</value>
      <webElementGuid>c15c8f5e-535a-401b-b2d9-6853e378f2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input agr-form-select agr-width-hundred mandatory</value>
      <webElementGuid>e170e17a-12f6-4186-9fe6-2741d25ce54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b7094ad-6863-4330-b874-6585d2cc53b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>444ab215-1e15-4373-8be6-f9f7627e52ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MandatoryGeneralWeighingVariantsPostpackPrepackBundleRental</value>
      <webElementGuid>4e3e8b99-ebf1-4d79-b9d8-025488a73c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchandise_type&quot;)</value>
      <webElementGuid>57032152-d41b-488e-a72a-e87cc750a30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='merchandise_type']</value>
      <webElementGuid>1946d81c-572e-4f5c-ab0d-a70e6d469edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='merchandise_type_container']/div/select</value>
      <webElementGuid>aef8a6f2-650f-48d7-aa0a-c38ae262dc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Type'])[2]/following::select[1]</value>
      <webElementGuid>31a9402b-7e67-4e4c-a1e0-fcf4d3f94ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory Control'])[2]/following::select[1]</value>
      <webElementGuid>d7afd103-f56f-4b5d-85d7-dddbf8be28b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Inventory'])[1]/preceding::select[1]</value>
      <webElementGuid>ed04047c-b5ea-4a5d-9e0a-e8fb776fb77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[7]/preceding::select[1]</value>
      <webElementGuid>2c130e87-5c5d-4046-9f6d-7516c5c1da06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>05543676-e827-4b7d-b35f-69c7e4fb8817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'merchandise_type' and @name = 'itemBomForm.merchandiseType' and (text() = 'MandatoryGeneralWeighingVariantsPostpackPrepackBundleRental' or . = 'MandatoryGeneralWeighingVariantsPostpackPrepackBundleRental')]</value>
      <webElementGuid>b2f3cf09-b6a4-4625-b48e-5254d4cea334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
