<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancel</name>
   <tag></tag>
   <elementGuidId>35d25618-3696-4b0b-8778-f4db76f6ff9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='back']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#back > span.agr-display-inline.tpz-fnt2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e249ab52-fe43-46ba-8a05-b85df021825a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-display-inline tpz-fnt2</value>
      <webElementGuid>0de59e67-7014-4644-9df8-2a6ba690cb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>85b40af2-e4cf-4c4d-a118-19bdfc27477a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back&quot;)/span[@class=&quot;agr-display-inline tpz-fnt2&quot;]</value>
      <webElementGuid>b14f7775-bb15-4caa-8e7a-39ab2a8794df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='back']/span</value>
      <webElementGuid>e45fabbd-be3d-443b-ba52-0c49f43e0ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save : Store Inventory'])[1]/following::span[1]</value>
      <webElementGuid>2a5e20b7-0e61-4d08-989a-61dc71e0e127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[4]/following::span[1]</value>
      <webElementGuid>b5fcf9bd-90c4-4e02-8c4a-c8324c5cd422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::span[3]</value>
      <webElementGuid>6a925488-c81e-4bde-b518-a1a41470ec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/preceding::span[4]</value>
      <webElementGuid>bb4da11a-d84a-421f-897d-40c88096293b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/span</value>
      <webElementGuid>42c61699-f158-4422-affd-f8079daa38a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>7b82320b-5eca-4153-a147-b9714e09d811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
