<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MD-00001 - CCY</name>
   <tag></tag>
   <elementGuidId>578c9029-7578-4ad3-8851-6b1ca9da4f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-114</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-114']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13c47f75-6521-4776-b741-dcffb3a56a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-pri-fnt2 ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>1d80b017-e93a-4eda-a9c6-f822ad74e7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-114</value>
      <webElementGuid>9bdd27b6-38b3-4434-beb6-effac1949adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d4300047-d101-45e4-a856-3582f8bd4a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MD-00001 - CCY</value>
      <webElementGuid>35aed29a-96ce-4d19-b39d-bc022707d35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-114&quot;)</value>
      <webElementGuid>a8403876-d2d6-479a-9004-ee68509648d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-114']</value>
      <webElementGuid>f27022d0-9500-451d-8495-7e887ecd1d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-21']/li/div</value>
      <webElementGuid>d9c3b605-4e13-4d51-971f-2a902a5f3d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PHMA) PHARMACY A'])[2]/following::div[7]</value>
      <webElementGuid>ad20a08e-be04-469e-a42e-e518248576a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-114', '&quot;', ')')])[1]/following::div[28]</value>
      <webElementGuid>55764744-4db5-47a0-85ac-a68e56d65761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCY'])[1]/preceding::div[1]</value>
      <webElementGuid>8e5b25ba-99cf-4a9b-9187-4367820b0b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MD-00001 - CCY']/parent::*</value>
      <webElementGuid>2947b82c-0fb5-4ea7-ba75-29e83874bc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[21]/li/div</value>
      <webElementGuid>838a4142-d178-4e12-833d-6ce1c3967f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-114' and (text() = 'MD-00001 - CCY' or . = 'MD-00001 - CCY')]</value>
      <webElementGuid>7d7de972-a1b0-4f4c-94a0-74751f93222e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
