<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create</name>
   <tag></tag>
   <elementGuidId>5fd6507f-06c5-4e25-adce-a6ae0feafd72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tpz-med-fnt3.agr-sublist-list.agr-cursor-pointer.agr-front-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>586b8592-ed5d-48a9-a685-fd4863f4e89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-node</name>
      <type>Main</type>
      <value>130101</value>
      <webElementGuid>468c4ca7-0a98-4dbf-8227-f2c6976ba9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/goods-return/creation</value>
      <webElementGuid>8a8e2f0d-6151-407b-bd49-71d6eb662a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu</value>
      <webElementGuid>bf0d65c0-43b4-4ff1-bb50-dc4b724156f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Create
                                        </value>
      <webElementGuid>4aef9550-481c-4b0a-a986-a34e0a8bb969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agr_master_page&quot;)/div[@class=&quot;agr-sub-masterpage&quot;]/div[@class=&quot;agr-margin-top-30&quot;]/div[@class=&quot;agr-dashboard-sublist-container&quot;]/div[@class=&quot;row agr-destroy-margin&quot;]/div[@class=&quot;col-lg-4 agr-child-page agr-sublist agr-margin-bottom-15 agr-destroy-padding&quot;]/div[@class=&quot;agr-card-style agr-padding-all-10&quot;]/div[2]/div[@class=&quot;tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu&quot;]</value>
      <webElementGuid>3f910692-8d28-416f-8220-f77b7ff8b206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>1e852bb3-78a8-4774-8a0d-cd210b1ad8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[7]/following::div[2]</value>
      <webElementGuid>dfb1c44c-d5c2-45bf-a469-2dfdf6e4d3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHILD PAGES'])[1]/following::div[8]</value>
      <webElementGuid>a11268db-907f-46e0-823f-65a5cceae8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect'])[2]/preceding::div[1]</value>
      <webElementGuid>59f47648-63ee-449c-b53e-49d1c19b1012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release for Payment'])[2]/preceding::div[2]</value>
      <webElementGuid>7bd7556e-58c6-4f22-a845-214ac2931a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>f807a851-f1fa-45b2-aaf2-bde90f01c479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            Create
                                        ' or . = '
                                            Create
                                        ')]</value>
      <webElementGuid>78486147-51f4-41a6-96c3-6e51480e707a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
