<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EXCH - EXCHANGE</name>
   <tag></tag>
   <elementGuidId>7787297d-a316-4b78-a6a3-b601595a0c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-129</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-129']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d281517-d044-48f1-b929-aa28c2765974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-pri-fnt2 ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>08480ee9-c704-48e8-8ac5-72ec73449a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-129</value>
      <webElementGuid>6a0dea24-a1e3-43d3-82c8-944a8b6bf457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7d97deb5-773a-4e85-b00d-eb7c0ab53951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXCH - EXCHANGE</value>
      <webElementGuid>5875ba0b-46ce-47b0-b08c-e4a2395db69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-129&quot;)</value>
      <webElementGuid>a6918fe1-03ed-455e-8fb8-2f2fb571f895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-129']</value>
      <webElementGuid>6a4624e7-bfda-4ab5-a8b6-ee2c52a93048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-22']/li[2]/div</value>
      <webElementGuid>e2a0fc7a-d322-40ce-b231-bfd84be0d007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVET - POST EVENT EXCESS STOCK'])[1]/following::div[1]</value>
      <webElementGuid>5ba1d2c3-0f5c-444d-bc83-ee6e3187ccfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCY'])[1]/following::div[2]</value>
      <webElementGuid>419a4bfb-5398-4ef7-bb1f-b43021478674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPR - EXPIRY RELATED'])[1]/preceding::div[1]</value>
      <webElementGuid>a19f1164-ee81-41b8-a05d-7b69266fc603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='expr - expiry related'])[1]/preceding::div[2]</value>
      <webElementGuid>e76d2d70-9e3f-4357-9d37-776f1b119ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EXCH - EXCHANGE']/parent::*</value>
      <webElementGuid>ced68d15-ca1c-460b-916f-59a96314b080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>34254ade-2c8c-40b7-ac15-b21dee5ba99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-129' and (text() = 'EXCH - EXCHANGE' or . = 'EXCH - EXCHANGE')]</value>
      <webElementGuid>7ab9094e-fcd0-4123-aafe-e36790a38e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
