<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNIT_detList0.invoiceNumber</name>
   <tag></tag>
   <elementGuidId>a5daf316-84c6-466a-a5ce-2e51ffb96de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='detList0.invoice_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19efd87b-5656-4cfa-8938-8448d1e6c234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>360aae80-a9d7-4127-bb12-bfe577ade119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe6c7e9f-e15a-47ea-87c1-a7674ad39260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6fca672e-cb12-4ea2-b722-61dbc2e435af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input invoicenumber agr-form-input agr-display-inline agr-width-hundred pri-fnt3 mandatory agr-table-form-focusin</value>
      <webElementGuid>fd0d1d1a-adef-436d-b4f5-ae0281f1bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2670119c-44cd-435e-ad16-327a44ec0ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7042add-e913-48fc-b435-4cc70c955d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b570983-0d99-4212-a9af-180dd62b7ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-row</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1506dea5-2df9-4451-98d8-a80a699b2868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detList0.invoice_number</value>
      <webElementGuid>e95353ad-b00f-423d-93cd-d0384f9da748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detList[0].invoiceNumber</value>
      <webElementGuid>b0edaf0c-4c26-40e8-9e14-ed734dfa9c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detList0.invoice_number&quot;)</value>
      <webElementGuid>649add5f-4ec2-4a27-bae7-0c78f33f6a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='detList0.invoice_number']</value>
      <webElementGuid>e1f3c639-0feb-4b1c-a4c3-d1a64f0e81b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goods_return_checklist']/tbody/tr/td[5]/input</value>
      <webElementGuid>2a5988f7-ea0e-42e3-aa9e-5c1124e0e274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>7391f387-4124-4929-8c6a-e4db21be49bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'detList0.invoice_number' and @name = 'detList[0].invoiceNumber']</value>
      <webElementGuid>df3c0e24-ed7b-4bcd-a857-153bb42f2f47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
