<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_ticker agr-checkbox-style</name>
   <tag></tag>
   <elementGuidId>522bc8ff-3f4c-4be7-a9ff-fe29f8f76078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ticker.agr-checkbox-style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fb4ceb9-03e8-497d-8382-4e133548528c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6fc29df7-5149-482d-8ba4-563d2a0115fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ticker agr-checkbox-style</value>
      <webElementGuid>11d7cbca-35e7-4f02-b271-f97320e26de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-primary-key</name>
      <type>Main</type>
      <value>[{&quot;code&quot;:&quot;company&quot;,&quot;value&quot;:&quot;HTM&quot;},{&quot;code&quot;:&quot;subsidiary&quot;,&quot;value&quot;:&quot;001&quot;},{&quot;code&quot;:&quot;returnStore&quot;,&quot;value&quot;:&quot;0001&quot;},{&quot;code&quot;:&quot;returnNumber&quot;,&quot;value&quot;:&quot;67&quot;},{&quot;code&quot;:&quot;lastVersion&quot;,&quot;value&quot;:&quot;1678241689256&quot;},{&quot;code&quot;:&quot;creationMethod&quot;,&quot;value&quot;:&quot;WS&quot;}]</value>
      <webElementGuid>98f60e0c-af5d-4fa7-9090-09d4be6ac3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;center&quot;]/input[@class=&quot;ticker agr-checkbox-style&quot;]</value>
      <webElementGuid>6c327846-4d58-4551-b877-3b9a8e5b81ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[13]</value>
      <webElementGuid>aad0d11f-5b95-4f56-b77a-f2b031569a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td/input</value>
      <webElementGuid>42372746-5e39-4a8b-a645-f55220d36623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>3c6727b1-b860-4719-9c86-017f7bcd0ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>99ca9fb5-c73f-48a7-9baf-1f122db9ab33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
