<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_detList0.item</name>
   <tag></tag>
   <elementGuidId>610caae1-2819-4452-aa19-23d53436f8e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='detList0.item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>550e908e-196a-4d57-93df-ee98345c79a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e04ee36-1da2-4124-89b2-8089c33f5e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72c6937f-5c07-49d9-b2fb-ce0923a175f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a5b72384-e615-4f8b-8056-a95830c60b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input item agr-form-input agr-display-inline agr-width-thirty-five mandatory pri-fnt3 ui-autocomplete-input agr-table-form-focusin</value>
      <webElementGuid>08161628-feda-4d4a-a35b-31d9d4edd189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>4af99de4-14ee-4f79-90ef-125448b80587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51b38fd0-f468-4f1a-939b-077c42887a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad27bdee-51cd-4db3-ad66-817fb124c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filler</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84016e70-d1b4-4739-96d7-3d7434f10d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>c4698b85-1a71-4d1f-9efc-c153d5db438e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-row</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f7900f3-ceb7-40c7-9dc4-68786eb9a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detList0.item</value>
      <webElementGuid>689e7487-99b5-48a2-8ffb-575ee85a06e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detList[0].item</value>
      <webElementGuid>d72b4bfb-4283-4f31-9338-43061c3339eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detList0.item&quot;)</value>
      <webElementGuid>ebc3baec-d87f-4652-902a-5d3a8712a08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='detList0.item']</value>
      <webElementGuid>79f4d93b-384f-4979-b2cb-f1eba6cd141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goods_return_checklist']/tbody/tr/td[2]/div/div/input</value>
      <webElementGuid>1be9c50c-6ae4-4f52-998c-4f5bc6b033d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
      <webElementGuid>a4118456-7853-4b4f-9a7c-df546e4d3d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Mandatory' and @id = 'detList0.item' and @name = 'detList[0].item']</value>
      <webElementGuid>6a1566fa-1d7c-43d3-b27e-471d8f86e90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
