<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Return Number_returnNumber</name>
   <tag></tag>
   <elementGuidId>443d5cfb-bbed-49db-b474-fac903f0d8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_return_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_return_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c328b17-ac1d-4855-b2ec-c8c329512a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ff28802-74da-4ac0-97d2-615689ba6dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_return_no</value>
      <webElementGuid>e909e7b4-0bf0-4a5c-bbac-8a0b2bdbd017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>returnNumber</value>
      <webElementGuid>39ffc0f0-d77f-4795-a2d9-5ba43fdb97a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2dd42253-7dd6-4c39-8125-4b350a79bb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5c40bace-d72f-44cb-b459-5140ad010eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-form-input agr-width-hundred</value>
      <webElementGuid>0a515738-4e02-4223-8485-9b0a28d3bc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>48f4a0e4-331d-481c-934a-8b3ed0a32065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>9da49599-2f72-49bb-b7bb-c40a5d90db65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_return_no&quot;)</value>
      <webElementGuid>ef3e9ab1-379d-4634-86eb-f7b26f28dc49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_return_no']</value>
      <webElementGuid>dc7ed05d-59f8-407f-8e5f-99d3e43b92d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>5b7d9809-bac5-4ccc-8693-c9b1f02a7cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>e47f932b-73eb-4183-b914-fb5952cf26bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search_return_no' and @name = 'returnNumber']</value>
      <webElementGuid>25e3c1d3-9bf3-4200-991d-4d9229e54ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
