<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Store_storeDisplay</name>
   <tag></tag>
   <elementGuidId>d4219ff1-55a2-4ad3-a58f-56d97c0dca1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store_display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='store_display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10a216cb-f802-4dd9-9e27-57224396f61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a87051d1-032b-4c31-aad8-b82f222b5c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>store_display</value>
      <webElementGuid>e34048b7-6b65-4c35-9a4b-1ad6c57b4aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>storeDisplay</value>
      <webElementGuid>cf50288a-3cac-47c7-b2b8-bfe14b3d9216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a47cf48-83c7-4c8f-8e53-d011b74ea281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3919d91e-be22-4062-a0c0-ad69766e8cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-form-input agr-display-inline agr-width-hundred mandatory ui-autocomplete-input</value>
      <webElementGuid>4ac1dba7-01ce-46b4-a9d5-962e100ab2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>93d9a5db-da92-411b-892c-c4c5c9b9ba4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0689d532-25c3-4f69-bff0-e0285fea3fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>499b4cd3-bab3-4551-bc80-a800ca56cb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store_display&quot;)</value>
      <webElementGuid>e34c6e79-d329-46b6-90f1-82ff3abc2e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='store_display']</value>
      <webElementGuid>7373a764-7414-4bbb-b3f5-787dc0403cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_details']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>c3d1031a-eb9f-4074-b1dd-62c26de8137d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/input</value>
      <webElementGuid>caa04525-4987-4c7e-b75b-07f784809ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'store_display' and @name = 'storeDisplay' and @placeholder = 'Mandatory']</value>
      <webElementGuid>369af94c-6615-4b57-9903-6dc77bd6907d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
