<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNIT_detList0.expiryDate</name>
   <tag></tag>
   <elementGuidId>57d151e3-21a8-419d-943f-0070f1f17ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='detList0.expiry_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4c1664e-9e78-4546-be1f-858ada10dbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bc25041-16a4-435f-aff7-fbb30aceb48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7a163bb-59f7-49b9-b389-515a513d15e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-format</name>
      <type>Main</type>
      <value>yy-mm-dd</value>
      <webElementGuid>e293da74-5046-4787-ba20-ce4ce911c87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fb6e1487-f333-41b8-83e7-06db4776c4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4b5f417-b255-44b3-95d1-f82357bc2a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>yy-mm-dd</value>
      <webElementGuid>a53c85c5-f040-4057-8dfd-a5f4751ff1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-row</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a408fa1-6af1-41c7-9479-aad03e3df5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detList0.expiry_date</value>
      <webElementGuid>b6bf301d-5204-44d0-b0ef-b49fb5cc7b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detList[0].expiryDate</value>
      <webElementGuid>f95bc407-d3a7-4ffe-89b0-5ca1738e508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-input date-picker expirydate agr-form-input agr-display-inline agr-width-hundred pri-fnt3 hasDatepicker agr-table-form-focusin</value>
      <webElementGuid>d4651c6a-de66-4c5d-ae74-af237223dd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detList0.expiry_date&quot;)</value>
      <webElementGuid>ffbf96b1-365f-4013-9eab-f4ad9f5a4d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='detList0.expiry_date']</value>
      <webElementGuid>92116d86-f7b5-4b7e-9e60-fcecf04cba62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goods_return_checklist']/tbody/tr/td[8]/div/div/input</value>
      <webElementGuid>0229e8e0-2b90-4b52-86dc-046b8f675a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/input</value>
      <webElementGuid>d1f95f8d-dc1d-46c0-8115-d815e3ded37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'detList0.expiry_date' and @name = 'detList[0].expiryDate']</value>
      <webElementGuid>1f57ca58-0e99-4645-95c1-c4c53043ac59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
