<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exp Collection Date_supplierCollectionDate</name>
   <tag></tag>
   <elementGuidId>a762cdf5-d6d0-458f-9a36-cbc5ef5e8754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supplier_collection_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supplier_collection_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8ac5425-764f-4af6-843a-2a706113d610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c36a3655-afdf-47b1-9dab-c01a60555211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supplier_collection_date</value>
      <webElementGuid>61d78b85-a1a0-4175-86f9-a267084ae9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supplierCollectionDate</value>
      <webElementGuid>356a6f12-960b-40ad-b553-a3b51a6cefec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0571a581-59f3-4033-ad93-0bc7d648adc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-format</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>77b04afd-e58e-4fd1-bef5-550202d693ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-input agr-form-input agr-display-inline agr-width-hundred date-picker agr-form-input agr-display-inline agr-width-hundred mandatory hasDatepicker</value>
      <webElementGuid>ac4f76d7-627b-4974-bb54-2271526495fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2d1067be-0379-4b21-b466-af41ace9a7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY-MM-DD</value>
      <webElementGuid>3a1ba5c6-6756-4a32-9365-4167e24121ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cd73551f-6e41-46f2-8679-0a515e56e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supplier_collection_date&quot;)</value>
      <webElementGuid>42c9b40e-13e1-4dcc-b4a1-66bd77394657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supplier_collection_date']</value>
      <webElementGuid>1c6a1fd4-0d7a-41b6-be88-b5a6e8b7a2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_details']/div[4]/div[2]/div/input</value>
      <webElementGuid>5f4bf151-dbf6-4011-bcb4-93e0873ddb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>9e31876b-6790-4328-8531-7f5d4aa099e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'supplier_collection_date' and @name = 'supplierCollectionDate' and @placeholder = 'YYYY-MM-DD']</value>
      <webElementGuid>554a9e60-02c2-44df-9920-dce649d35b40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
