<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNIT_detList0.unitCost</name>
   <tag></tag>
   <elementGuidId>3133ed03-a31e-4fb4-a8fa-72fadd744e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='detList0.unit_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543c7922-d3ee-47e7-a840-ec082b7bc0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adc4867f-d264-4206-8b1b-462776ae5c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f20311c-17bc-4d90-b686-0cc43c9ec28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>06211d21-8de9-45a1-9ad1-e0eb487819a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input unitcost agr-text-right agr-form-input agr-display-inline agr-width-hundred numeric pri-fnt3 agr-table-form-focusin</value>
      <webElementGuid>0c7c8fb3-c6c5-40ff-a714-c7b3dae9d0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>48c3710d-f820-4c35-8772-c645d7c62430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85d4b2a9-3d30-48be-a811-03366da3075a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>9999999999.99</value>
      <webElementGuid>ef6e705a-31d5-4d8a-be14-df2ccd7336f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>205b3308-d699-40aa-a0c2-290f4f5225ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-row</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcfb5c22-e825-4721-9d0d-f4f9e6d43867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detList0.unit_cost</value>
      <webElementGuid>a1b3b014-0d80-44b6-a356-f04091ac5441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>detList[0].unitCost</value>
      <webElementGuid>a59b1794-b875-41d5-a4cb-9576896b4621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c487397-b726-4bbe-bfe0-4d5d52ab5cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-digits</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a80a16cc-5e98-49b7-ae68-9ee4902cbb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-error</name>
      <type>Main</type>
      <value>Unit Cost cannot be lesser than 0.</value>
      <webElementGuid>afd80fe0-7a3d-4f04-b5c9-5d6b40580b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max-error</name>
      <type>Main</type>
      <value>Unit Cost cannot be greater than 9999999999.99.</value>
      <webElementGuid>5d36da1a-7e23-412c-8c45-eb9e7f7e7c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae8f53d6-bec1-4eda-b3c5-79205bc8158a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detList0.unit_cost&quot;)</value>
      <webElementGuid>50871642-509e-4cc3-9701-c60ad6156451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='detList0.unit_cost']</value>
      <webElementGuid>998a7aa9-c8a1-4306-90b1-97e3a814a8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goods_return_checklist']/tbody/tr/td[9]/input</value>
      <webElementGuid>ea0f2aa5-9f6f-40c7-883d-98e2920766ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>0f201448-2659-48d2-ae45-dd3ddd58f9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '0.00' and @id = 'detList0.unit_cost' and @name = 'detList[0].unitCost']</value>
      <webElementGuid>7e688668-538b-489e-ba62-aeddb74be060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
