<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Group_itemGroupDisplay</name>
   <tag></tag>
   <elementGuidId>566a5e2d-3770-4770-9148-a9dc8ec2e96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_group_display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='item_group_display']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc26caec-22f3-442d-9861-4facdb3a0b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96f2e8c3-a8f5-4d3f-b4ac-34a163ef3851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_group_display</value>
      <webElementGuid>ee77c587-2071-4682-a700-540b08e4ae2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemGroupDisplay</value>
      <webElementGuid>7a86e6e9-2fa9-435e-b95e-90a238c12ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7a236b8-87b7-480a-b33b-5b059d2cb792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>07404468-5416-42bd-8ad2-d62c1c956fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-input agr-form-input agr-display-inline agr-width-hundred mandatory ui-autocomplete-input</value>
      <webElementGuid>f2177567-2df9-45ac-afc4-ed47ec41571b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mandatory</value>
      <webElementGuid>1f5a2b69-a7c4-4317-9dd9-491c24a405c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2b2e952f-2f4d-45ad-b22c-ba50b15c4541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(function(that){const clear=that.nextElementSibling;if(clear){if(that.value.length>0){if(clear.classList.contains('agr-hidden')){clear.classList.remove('agr-hidden');}}else{if(!clear.classList.contains('agr-hidden')){clear.classList.add('agr-hidden');}}}})(this);</value>
      <webElementGuid>aaf40813-f1d7-44c7-a9e0-f4c085c691d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_group_display&quot;)</value>
      <webElementGuid>3f549d05-ec7f-4149-96f7-39f8b1395277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='item_group_display']</value>
      <webElementGuid>c6954cf5-25c5-433a-92cb-79fd5f49bacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return_details']/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>74a3d3d6-a07e-4b17-9980-9fbb75889fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/input</value>
      <webElementGuid>0be9d47c-7a2e-4320-b768-eb5c7d92b8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'item_group_display' and @name = 'itemGroupDisplay' and @placeholder = 'Mandatory']</value>
      <webElementGuid>19b5d9b7-3c9b-4aca-97e9-9d2046fe2236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
