<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>4c289410-ade5-4e23-a915-2b8fe9cf0d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.agr-display-inline.cry-fnt2.agr-margin-left-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='inquiry_search']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>409bcf02-e317-4113-9ce0-c7b9eca0ecb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-display-inline cry-fnt2 agr-margin-left-5</value>
      <webElementGuid>8b8cda3e-6d10-41d3-ad34-59ac6a6cfbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Search</value>
      <webElementGuid>ae3444de-83ec-4c69-8cf9-cd4f0325e930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inquiry_search&quot;)/span[@class=&quot;agr-display-inline cry-fnt2 agr-margin-left-5&quot;]</value>
      <webElementGuid>6291fc87-cde3-4056-ac58-7a16cd86e140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='inquiry_search']/span</value>
      <webElementGuid>b6d8c45a-8fad-422c-93b5-2e286b870179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Filter'])[1]/following::span[1]</value>
      <webElementGuid>ce9d1316-4c2b-42dd-81fa-c02ca070995b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Payment'])[2]/following::span[2]</value>
      <webElementGuid>e21c1449-4785-4563-bedb-ba6b0ec3de05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Number'])[2]/preceding::span[1]</value>
      <webElementGuid>b72b16d1-16d8-4d1a-9c41-ed02f3df44ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[4]/preceding::span[1]</value>
      <webElementGuid>88b73561-1b60-44e4-8f22-41e20c201d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>28546f55-a3e2-4e99-bcfa-62d3a5fc7693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>d962c336-05fb-4e2b-b632-4f7f89f4bb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        Search' or . = '
                        Search')]</value>
      <webElementGuid>400fefc5-1ed9-427f-90f3-5d39329e15db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
