<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Complete</name>
   <tag></tag>
   <elementGuidId>300ea482-c347-4a32-900b-7929ef9fc867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save_complete > span.agr-display-inline.cry-fnt2.agr-margin-left-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='save_complete']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b8b703f-ea36-450a-bfa1-47c426c3aec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-display-inline cry-fnt2 agr-margin-left-3</value>
      <webElementGuid>2a6a47c0-7b00-4d42-b944-7a07723e27e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>e8e11162-6de6-41c8-97db-523b072c6800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_complete&quot;)/span[@class=&quot;agr-display-inline cry-fnt2 agr-margin-left-3&quot;]</value>
      <webElementGuid>d5ab4f88-414c-4fdd-b1e9-0d95188341f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='save_complete']/span</value>
      <webElementGuid>2d0b0f6f-1f96-462f-9371-110293c3fbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::span[1]</value>
      <webElementGuid>872f6d33-6757-4207-a759-4acb31d86cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[2]</value>
      <webElementGuid>407a564e-9b35-4d6a-b594-65bc3a7142e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Setting'])[1]/preceding::span[1]</value>
      <webElementGuid>24de3c48-dbe9-4dac-a664-5b71540cedb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::span[1]</value>
      <webElementGuid>1f84b8f0-dad9-4540-9613-b3d60a953f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complete']/parent::*</value>
      <webElementGuid>d1a8e007-6f41-41af-892f-5c54b6681ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/span</value>
      <webElementGuid>b30bbd71-99d7-4581-bf00-9ada2eca8a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Complete' or . = 'Complete')]</value>
      <webElementGuid>22c0ee1b-438c-4484-a5fa-3e62d422bcc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
