<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_1Advanced SearchCOCONUT SHAMPOO D1UNITCo_170880</name>
   <tag></tag>
   <elementGuidId>450f8e91-18f8-42d6-a281-eb0939e4e45d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goods_return_checklist > tbody > tr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goods_return_checklist']/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>3a60cb14-d0cc-448d-b6bd-93364de020e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Advanced SearchCOCONUT SHAMPOO D1UNITCost Lookup </value>
      <webElementGuid>d3a0bd55-3e22-488a-8c32-aefbcfd41f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goods_return_checklist&quot;)/tbody[1]/tr[1]</value>
      <webElementGuid>3c6d803d-7523-4bd6-9737-6c8a62e2472f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goods_return_checklist']/tbody/tr</value>
      <webElementGuid>7a754370-5d35-451e-8309-f5d6ac553515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::tr[1]</value>
      <webElementGuid>f99d0728-358c-435d-ae19-5fe7e2bca142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Cost'])[4]/following::tr[1]</value>
      <webElementGuid>79d26350-c31c-4b59-b4d3-ef8065321839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr</value>
      <webElementGuid>a023e833-b3a5-42d1-b0b8-84e7c801f6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[(text() = '1Advanced SearchCOCONUT SHAMPOO D1UNITCost Lookup ' or . = '1Advanced SearchCOCONUT SHAMPOO D1UNITCost Lookup ')]</value>
      <webElementGuid>4f4463f0-8ef9-4c65-a3ec-dccf8984c845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
