<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Collect</name>
   <tag></tag>
   <elementGuidId>40a2f877-dd76-4f92-95e0-91d787173e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d16f116-648d-43b3-ad03-253e5aedd58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-node</name>
      <type>Main</type>
      <value>130103</value>
      <webElementGuid>bf647270-64af-4866-a870-a1377a611fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>/goods-return/approval</value>
      <webElementGuid>72149666-5a9c-4587-a9eb-6daad35cc292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu</value>
      <webElementGuid>78993eb0-fac5-4f64-a6a0-0f07b8f576b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Collect
                                        </value>
      <webElementGuid>fad6b8f3-dcd1-41b2-8ebe-ed438a188745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agr_master_page&quot;)/div[@class=&quot;agr-sub-masterpage&quot;]/div[@class=&quot;agr-margin-top-30&quot;]/div[@class=&quot;agr-dashboard-sublist-container&quot;]/div[@class=&quot;row agr-destroy-margin&quot;]/div[@class=&quot;col-lg-4 agr-child-page agr-sublist agr-margin-bottom-15 agr-destroy-padding&quot;]/div[@class=&quot;agr-card-style agr-padding-all-10&quot;]/div[2]/div[@class=&quot;tpz-med-fnt3 agr-sublist-list agr-cursor-pointer agr-front-menu&quot;]</value>
      <webElementGuid>b6ee2ccf-caba-4f6e-a5fb-23a837aa3093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='agr_master_page']/div/div/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>1990d84d-9702-4ddf-acf4-a578658d384d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[25]/following::div[1]</value>
      <webElementGuid>be3fad87-f946-40c4-b780-a3215a7861e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[7]/following::div[3]</value>
      <webElementGuid>6ea2a4ff-cb8f-42f3-aea2-81518fbf8fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release for Payment'])[2]/preceding::div[1]</value>
      <webElementGuid>eff40557-ac07-487f-9a56-42f49edf3d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Debit Note Matching'])[2]/preceding::div[2]</value>
      <webElementGuid>294f61a9-ca67-4fc2-bed0-a76bfd1ae6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>d90f1689-43e3-46aa-bf54-76d5d271afff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            Collect
                                        ' or . = '
                                            Collect
                                        ')]</value>
      <webElementGuid>6cec42f3-aae1-4a64-a263-d2cc774075b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
