<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0001 - (PHMA) PHARMACY A</name>
   <tag></tag>
   <elementGuidId>be7474ea-10c9-4c7d-b652-cb5535edf526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43a8874a-adde-4f45-b3ca-340be82123e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agr-pri-fnt2 ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>1d06cb03-4b03-40d7-8742-bb470747e1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-14</value>
      <webElementGuid>416ab780-0ccb-45d8-8906-4d639b6d6f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8b3f0607-b0f6-484e-ba9f-4729938653a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0001 - (PHMA) PHARMACY A</value>
      <webElementGuid>e7333fb4-ed18-4c13-a502-6f6fcda1d606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-14&quot;)</value>
      <webElementGuid>d985bf47-96ac-447f-acb8-62be1ddad5be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-14']</value>
      <webElementGuid>eed48f98-4ad1-4be3-b39d-9b64a4dadcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li/div</value>
      <webElementGuid>0a252ad4-af11-4e52-a85e-c70b33d63ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-14', '&quot;', ')')])[1]/following::div[2]</value>
      <webElementGuid>7af62dc3-8024-46b9-bcc7-3d657b437153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PHMA) PHARMACY A'])[1]/preceding::div[1]</value>
      <webElementGuid>876e8deb-d667-4e35-9471-160fbc142498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0001 - (PHMA) PHARMACY A']/parent::*</value>
      <webElementGuid>5f5820bf-9a77-4268-ac70-6b15aa509534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li/div</value>
      <webElementGuid>8b07435e-b154-40f2-807f-7baeae130d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-14' and (text() = '0001 - (PHMA) PHARMACY A' or . = '0001 - (PHMA) PHARMACY A')]</value>
      <webElementGuid>1049f7f6-cad1-491d-a4fe-57509bc26f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
