<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_ticker agr-checkbox-style</name>
   <tag></tag>
   <elementGuidId>fde187a2-5142-4c83-ad45-d66047fb652d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ticker.agr-checkbox-style</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a99a1239-aefa-4e8a-9eb6-55247f0e23a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d9960f7b-5a0a-47b1-957b-b008add3a5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ticker agr-checkbox-style</value>
      <webElementGuid>c28c8668-789a-4d91-bc1b-f7d66571e162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-primary-key</name>
      <type>Main</type>
      <value>[{&quot;code&quot;:&quot;company&quot;,&quot;value&quot;:&quot;HTM&quot;},{&quot;code&quot;:&quot;subsidiary&quot;,&quot;value&quot;:&quot;001&quot;},{&quot;code&quot;:&quot;returnStore&quot;,&quot;value&quot;:&quot;0001&quot;},{&quot;code&quot;:&quot;returnNumber&quot;,&quot;value&quot;:&quot;23&quot;},{&quot;code&quot;:&quot;lastVersion&quot;,&quot;value&quot;:&quot;1656656608315&quot;},{&quot;code&quot;:&quot;creationMethod&quot;,&quot;value&quot;:&quot;WS&quot;}]</value>
      <webElementGuid>1b17ef9f-6549-40a3-bbb3-68360017820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;center&quot;]/input[@class=&quot;ticker agr-checkbox-style&quot;]</value>
      <webElementGuid>364e0e57-965f-437d-8c16-382549aee215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[9]</value>
      <webElementGuid>ee6f27d6-8acf-4ebf-a8e2-917251487539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td/input</value>
      <webElementGuid>4bc41ea2-cebc-4729-89b1-6f930ca1e6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>9d46603b-ebe5-457e-8055-16a9a898edd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>71be70ab-6c98-4689-9372-a720039c371e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
