<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maintain Sales Transaction</name>
   <tag></tag>
   <elementGuidId>be0d0a6d-3f6c-4017-9f2f-34e5dcf52a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@value='788'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c23bbd85-0215-4bb1-8174-7ce0b9ab07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ChangeDescColor(this); ChangeImage(795); closeMenuFrame();</value>
      <webElementGuid>260e48b9-7624-4d1e-b4e9-75c40371ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Maintain Sales Transaction</value>
      <webElementGuid>c2a1398c-5bbc-4c31-a248-71355bd3e785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../SP/SlstxSearch.jsp?ACTION=INIT</value>
      <webElementGuid>ce842537-a048-4cb7-b89f-995a66c2be0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>mouseOutHandler(this)</value>
      <webElementGuid>063122a3-5e9e-40e0-971e-838e33d3adb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>mouseOverHandler(this)</value>
      <webElementGuid>e42d0824-ef4d-4b2a-8133-9c892225a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5425f2bc-1061-436a-9e0f-2a440bc3ed09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tracker</value>
      <webElementGuid>0fe3c0c6-a1e4-4432-82c4-27829996d34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>788</value>
      <webElementGuid>928c978e-e13b-46e1-85b0-4197b0cf46e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintain Sales Transaction</value>
      <webElementGuid>2159bae6-bf36-46b3-8129-44de9f5dcfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C-63&quot;)/table[7]/tbody[1]/tr[1]/td[@id=&quot;LI-63&quot;]/a[@class=&quot;tracker&quot;]</value>
      <webElementGuid>4d394d87-7991-4748-b911-dad68cda9d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AVN SIT/Page_PROFIT/frame_concat(id(, , contentFrame, , )frame1_a1fbfc</value>
      <webElementGuid>14135f9e-565f-4652-b639-45a75ec91fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@value='788'])[7]</value>
      <webElementGuid>c8eb7339-79ce-46de-836d-57ecd6cd3a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='LI-63']/a)[7]</value>
      <webElementGuid>fd136eee-347a-423e-9cdb-a66e438f3967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Maintain Sales Transaction')]</value>
      <webElementGuid>72e6d37b-83b0-4442-af9c-e8870a0db38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquire Upload Process Status'])[21]/following::a[2]</value>
      <webElementGuid>6cd0206e-2852-44c2-add3-79bd8ba6c680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Status Viewer'])[13]/following::a[4]</value>
      <webElementGuid>12e3e6a1-c662-4d2c-b299-d3f5adb76713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Sales Transaction'])[1]/preceding::a[2]</value>
      <webElementGuid>45ec65c5-60e9-46a0-8763-1442f68a4d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amend Sales Transaction'])[1]/preceding::a[4]</value>
      <webElementGuid>8982b81a-ca88-4b71-93c3-11a20daae7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintain Sales Transaction']/parent::*</value>
      <webElementGuid>a5b17386-c41e-46ae-baac-977d82f78b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../SP/SlstxSearch.jsp?ACTION=INIT')])[2]</value>
      <webElementGuid>1a8fe5c3-20d6-415c-830e-111c53aa4b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/table[7]/tbody/tr/td[2]/a</value>
      <webElementGuid>bb1fbc2d-3186-4fc1-bb4c-b0b8d06cd3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Maintain Sales Transaction' and @href = '../SP/SlstxSearch.jsp?ACTION=INIT' and (text() = 'Maintain Sales Transaction' or . = 'Maintain Sales Transaction')]</value>
      <webElementGuid>68d617cc-d5a9-4449-aad0-4ed4fb656375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
