<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Body</name>
   <tag></tag>
   <elementGuidId>cb387e0c-71dc-4634-bff0-2be61db2044a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>ec944dd1-2f6b-4584-a068-405645c18279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>2dfc3f7b-ee2b-4bc5-901d-8cabe8067f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
