<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_concat(id(, , menu, , )frame1)_MenuHeader</name>
   <tag></tag>
   <elementGuidId>618bc0df-cf3d-4bb1-9791-66c2f1a4004a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;MenuHeader&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='MenuHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ba246dea-d6d1-44b7-9b07-a34b55a51feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MenuHeader</value>
      <webElementGuid>b1c4f742-00fa-43d1-8dc6-e506370d45a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/VNM/profit/AD/MenuHeader.jsp</value>
      <webElementGuid>05016845-b77f-4d62-aff8-40d25e55bd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7e4235a1-18d1-467f-99a9-f21f60158614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>b0752309-8764-474a-a924-f64d7b391647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/frame[1]</value>
      <webElementGuid>8eb06423-0068-4020-ace1-d8fb79ae3664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='MenuHeader']</value>
      <webElementGuid>edef11d1-1b4f-4209-ad58-4a4ca263a0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//frameset[@id='menu']/frame</value>
      <webElementGuid>0410f086-2db5-4f1d-b1e8-08093ce9cc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frameset/frame</value>
      <webElementGuid>2b019561-8d3c-4cb5-9865-d8afa1753087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'MenuHeader' and @src = '/VNM/profit/AD/MenuHeader.jsp']</value>
      <webElementGuid>a2869d36-6267-4bb3-a2c5-bb120c209366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
