<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_concat(id(, , contentFrame, , )frame1_a1fbfc</name>
   <tag></tag>
   <elementGuidId>a2cb45a3-b45c-4a11-9b32-bfa5ff1aff0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contents&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ad17f151-1462-43c3-8c78-2797efb5db8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contents</value>
      <webElementGuid>a38dd4e9-bab5-405a-bb90-e5b2fa96a3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/VNM/profit/AD/TreeMenu.jsp</value>
      <webElementGuid>625fd50c-fc4e-4a03-9c69-bf3d69c710fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>86b7689c-ce07-414b-a530-789f6c4e505d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a97c7af9-4a6c-45b6-801d-c340dd99e57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/frame[2]</value>
      <webElementGuid>e304fe1f-67e9-4645-bbfe-4998b38fffab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contents']</value>
      <webElementGuid>c635bd2d-0144-4325-a60a-20233589d9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//frameset[@id='menu']/frame[2]</value>
      <webElementGuid>d23c6a0f-331c-436d-bfe7-c9583d95a095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>97540032-fee3-4a98-9dc5-796ee50c0ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'contents' and @src = '/VNM/profit/AD/TreeMenu.jsp']</value>
      <webElementGuid>fb8a3bc9-8462-47b9-9054-4285a5552ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
