<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PROFIT Menu_ALLExpand</name>
   <tag></tag>
   <elementGuidId>5bc3286a-32e6-47f0-adca-11a36140b72e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ALLExpand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ALLExpand']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f7e3aba8-5811-4d96-8449-5b863494fac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ALLExpand</value>
      <webElementGuid>989ac734-afda-4e64-8d60-20001afb5662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ChangeTree(this.id);</value>
      <webElementGuid>80a0b0b9-62b1-4fd2-bede-598f66407f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2c70b2b3-280d-4d4e-b756-c2f956aa9fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Expand all menu</value>
      <webElementGuid>43b8f24d-768d-4ffe-abe0-53ab2fe650a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/expandMenu.gif</value>
      <webElementGuid>7c986de4-fd1e-48b9-bd38-58094d473049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>97f4e9f9-ad00-4400-abd1-fbdbf2a42bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>430cf99b-5e0b-410c-862f-84083f502b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ALLExpand&quot;)</value>
      <webElementGuid>3a1b3b6c-098b-4365-b31f-6808dd9c6d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AVN SIT/Page_PROFIT/frame_concat(id(, , menu, , )frame1)_MenuHeader</value>
      <webElementGuid>f52d8f8c-15c5-4c9e-8b50-7f6281a09fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ALLExpand']</value>
      <webElementGuid>6798c05c-8526-4f1d-be26-f522bfd7ba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Expand all menu']</value>
      <webElementGuid>b59f0b47-3d80-4ac2-81da-ea53a37b4a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f8551b7a-358f-4e95-ada5-8781123522ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ALLExpand' and @alt = 'Expand all menu' and @src = '../images/expandMenu.gif']</value>
      <webElementGuid>6817b7c1-747f-48e3-94d9-c4b167922cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
