<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_txtPassword</name>
   <tag></tag>
   <elementGuidId>5269e819-07d5-4496-b31c-21a5d29af3c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df476363-4a3b-4805-b48f-6b86687503b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>95bcf2fc-f5e8-4c0b-a39b-aa31495d5b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatory</value>
      <webElementGuid>55f01f0e-bed3-4e5a-a28b-88c039ecc18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>f08e87ca-ef8c-424f-86b2-c8cc8f9c1060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>ffa7f97d-a379-4657-93b7-eaa48fb2cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>loadCapt();</value>
      <webElementGuid>19d787d6-f169-42cd-ba2f-6f3ede25de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>loadCapt();</value>
      <webElementGuid>2d5644b8-c326-4b8c-b2ea-6b6e5ca12f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[3]/td[2]/input[@class=&quot;mandatory&quot;]</value>
      <webElementGuid>31176024-d63d-4cf1-8e5f-18a7ad276481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtPassword']</value>
      <webElementGuid>910154e1-e663-4f5f-8acb-e9f75e985362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[3]/td/table/tbody/tr[3]/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>5f991409-8235-464d-ac67-ad2e42170b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>0a9325a3-f6ef-47c9-9625-a41a8c4da571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'txtPassword']</value>
      <webElementGuid>9d7c750d-e654-42db-95b5-faf5e0c63c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
