<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_btnLogin</name>
   <tag></tag>
   <elementGuidId>a8b44770-cfca-475d-9727-d65f27c5650f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnLogin&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b661835-669e-4696-978a-068303cfb3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>login();</value>
      <webElementGuid>edb49520-0c94-4dfb-af2f-ce69ec423e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>55fc1966-35d4-4075-afaa-9a9cbeb9800a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e0f9e3dc-922b-44d9-86db-eb1b93c6535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>75a8e9ac-3b7b-4247-92cc-15e93c20d732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-login</value>
      <webElementGuid>57d839b9-a4b4-490c-b33b-c204508f9cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/table[2]/tbody[1]/tr[1]/td[3]/input[@class=&quot;button-login&quot;]</value>
      <webElementGuid>13d63eae-6e98-4e5c-9eaf-c799d323ccde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnLogin']</value>
      <webElementGuid>6bea34e5-a23a-46ea-b9e6-5192d22109c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[3]/td/table/tbody/tr[3]/td/table[2]/tbody/tr/td[3]/input</value>
      <webElementGuid>3064f3d9-7ec8-4e36-b4ef-cbec3cca84bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>f3ef56a9-31fd-46a2-9131-17f98c30e984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnLogin' and @type = 'submit']</value>
      <webElementGuid>5e0626a7-b5c9-464b-8871-e5f28ab09cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
