<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Back</name>
   <tag></tag>
   <elementGuidId>4764d3a1-ad68-44c2-93fa-75f777aada11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#back_main_search > span.tpz-fnt2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='back_main_search']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cd7aa2ee-c2bc-4343-ad1c-e29eb86da88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tpz-fnt2</value>
      <webElementGuid>8b0ac2cd-3d2f-49a0-8b9b-fac6834f378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Back</value>
      <webElementGuid>17ccd277-81d1-4810-a1fb-80444b6e2273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back_main_search&quot;)/span[@class=&quot;tpz-fnt2&quot;]</value>
      <webElementGuid>b5abee88-16bd-46c9-b724-302f4c7093f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='back_main_search']/span</value>
      <webElementGuid>861e1f74-912b-450d-abdd-b65c0b8d76de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/following::span[2]</value>
      <webElementGuid>dc071acd-f5f7-4d07-9536-682b99b680be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::span[3]</value>
      <webElementGuid>0e428441-c5e3-4837-aa01-0cfe575ce891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[4]/preceding::span[2]</value>
      <webElementGuid>a8390ed3-78a0-42d6-a078-e0b6d6012546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity Inventory'])[2]/preceding::span[2]</value>
      <webElementGuid>fc817315-4ecd-4bd9-9ae0-9d5a52f1f739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>2a22bf00-cdf5-4427-97be-e396c17b4d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/a/span</value>
      <webElementGuid>782476ba-7cb2-42ed-ab27-cf0d566a1bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Back' or . = ' Back')]</value>
      <webElementGuid>804a3018-2dfd-4417-948f-d4ddd5f241c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
