<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0.000000</name>
   <tag></tag>
   <elementGuidId>3fab9a2e-7a85-4beb-b245-249799d14a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pri-fnt3.datatable-cell.text-right.class-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result']/tbody/tr/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5301a515-950a-4085-86f6-8f0d43514bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pri-fnt3 datatable-cell text-right class-7</value>
      <webElementGuid>eb32ddb8-6dd8-40a7-a475-33fcaaae1a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>63bcd090-20e3-4259-9269-6571c96e9d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Quantity Allocated</value>
      <webElementGuid>cdc631c8-e024-49e4-bd25-99b44709f5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.000000</value>
      <webElementGuid>ba0c0ef8-e51f-4159-8cd6-93327b4edf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;pri-fnt3 datatable-cell text-right class-7&quot;]</value>
      <webElementGuid>8e7dc8de-20d8-4cfd-86cb-380c296ea3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td[9]</value>
      <webElementGuid>dcec54b0-34f5-4a71-ad70-b9bd324a9ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::td[5]</value>
      <webElementGuid>a85016a6-4795-43c8-9110-9b5fc44d5902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COCONUT SHAMPOO D'])[1]/following::td[6]</value>
      <webElementGuid>ab175731-1e4b-44bd-b749-311dc9a93518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::td[6]</value>
      <webElementGuid>24b318cb-ba5f-42ae-8eb8-4912b3f85e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/preceding::td[6]</value>
      <webElementGuid>4f98236e-5f40-4878-989d-eb08cd75f46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.000000']/parent::*</value>
      <webElementGuid>6e7f2860-32da-417a-8d5f-538fcd4f1632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]</value>
      <webElementGuid>cfee4e33-8d69-4f32-b1ea-9ef5b8938ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '0.000000' or . = '0.000000')]</value>
      <webElementGuid>00c0e924-12ee-4ac5-b9e0-0f533576da9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
