<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_40.000000</name>
   <tag></tag>
   <elementGuidId>2ed40c8c-65a1-4a3c-84d8-5a4bb6fb54e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pri-fnt3.datatable-cell.text-right.class-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result']/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>527aa70b-dd27-4e94-9655-913b50e347de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pri-fnt3 datatable-cell text-right class-3</value>
      <webElementGuid>1d3d275d-7e9f-4d86-be8a-5b629151785e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>302e83bb-1c0a-4755-b045-9434d481d529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Quantity Inventory</value>
      <webElementGuid>14b2ad31-a17e-4d1a-961d-52dc33b7ebd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40.000000</value>
      <webElementGuid>072fe490-bafe-4ffe-b376-70c3b5a60db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;pri-fnt3 datatable-cell text-right class-3&quot;]</value>
      <webElementGuid>ce6c9544-c270-44a5-91db-f0310d1006be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td[5]</value>
      <webElementGuid>6301f874-371f-4cd1-a852-46b08be1ff94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::td[1]</value>
      <webElementGuid>8202580b-0f9c-410d-9b88-d80d7d48ed0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COCONUT SHAMPOO D'])[1]/following::td[2]</value>
      <webElementGuid>33a725e3-4791-4200-8f51-4d2786ed4e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::td[10]</value>
      <webElementGuid>caf9dcc8-2343-4d77-9bd8-c8e59098e917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/preceding::td[10]</value>
      <webElementGuid>c293972f-91ae-452b-9cff-15945f8ac36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40.000000']/parent::*</value>
      <webElementGuid>54e1fc66-0f76-4d7c-b69d-68e0395116f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>6dc6d81e-4e83-409c-9c79-5904e417be7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '40.000000' or . = '40.000000')]</value>
      <webElementGuid>7cea966c-6ed7-43f1-95de-58a364bcabda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
