<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_56.000000</name>
   <tag></tag>
   <elementGuidId>035dd163-cad5-4509-8733-c252fde42d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pri-fnt3.datatable-cell.text-right.class-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result']/tbody/tr/td[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6913abac-95ff-4879-9586-94f5067313e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pri-fnt3 datatable-cell text-right class-5</value>
      <webElementGuid>584ca251-433a-4a95-b16d-82b29f5c7deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7ea91a18-c145-4ac8-834f-79e986821f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Quantity On Order</value>
      <webElementGuid>1191c0e5-f3c0-451f-bbff-7df55a4793cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>56.000000</value>
      <webElementGuid>29e17edf-40c6-4f82-bf2d-9d1425ecc8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;pri-fnt3 datatable-cell text-right class-5&quot;]</value>
      <webElementGuid>0db304d3-9e82-4f12-a587-4f9e251d851c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td[7]</value>
      <webElementGuid>64a876d8-b870-4b79-966b-aee88314e71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::td[3]</value>
      <webElementGuid>cf27192f-d36a-44ba-88f9-35e6003ea5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COCONUT SHAMPOO D'])[1]/following::td[4]</value>
      <webElementGuid>63cf36c4-52f1-4e1f-807a-c16341971d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::td[8]</value>
      <webElementGuid>a64a3d2a-16cd-4597-a3b6-f41c2f79c3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/preceding::td[8]</value>
      <webElementGuid>fb135ef6-2f80-4136-b5b4-a6b4e19da8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='56.000000']/parent::*</value>
      <webElementGuid>a97f8328-6837-4fdc-9920-3fc110b12ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>787a0d71-731e-4ce1-a5b4-15ab721ea34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '56.000000' or . = '56.000000')]</value>
      <webElementGuid>eae9cc3d-c688-4d7d-aedc-c80f1891cd8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
