<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_6.000000</name>
   <tag></tag>
   <elementGuidId>0f7f5d9c-1e13-4de9-89e6-1bacc244c2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pri-fnt3.datatable-cell.text-right.class-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result']/tbody/tr/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>566d8424-00c8-4f3e-b191-78c249e277e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pri-fnt3 datatable-cell text-right class-6</value>
      <webElementGuid>a777a211-6990-4270-962c-334e4b076324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5d9aad5f-e147-4ed2-b86d-480c7716724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Quantity Forecast</value>
      <webElementGuid>7f453694-9e10-442b-b03f-97e9fba358ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6.000000</value>
      <webElementGuid>588686d4-df19-43aa-9abf-d9610e0e30d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;pri-fnt3 datatable-cell text-right class-6&quot;]</value>
      <webElementGuid>5f01424c-196c-4ea6-9a19-719c4f85e13c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td[8]</value>
      <webElementGuid>74322fb2-d7cf-4522-9bf3-d82a3834f9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::td[4]</value>
      <webElementGuid>d67964ed-e7e6-4c0c-8753-ebf3258f477b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COCONUT SHAMPOO D'])[1]/following::td[5]</value>
      <webElementGuid>3e36dff0-5397-4392-b93f-253a0066b38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::td[7]</value>
      <webElementGuid>d4f4f8f4-cd3b-40be-8238-c4ce956a63ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/preceding::td[7]</value>
      <webElementGuid>cef5a741-0723-4bb8-873b-64e43f744413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6.000000']/parent::*</value>
      <webElementGuid>54144585-eaa6-41c1-b47e-c0e546375b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]</value>
      <webElementGuid>038c0c5e-1015-44c6-a720-094ce781ec51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '6.000000' or . = '6.000000')]</value>
      <webElementGuid>fd9e66e5-07fa-4d3f-a83c-a4e4b78d385b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
