<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_96.000000</name>
   <tag></tag>
   <elementGuidId>5ec92419-9054-4633-94c6-132b0ce4382e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pri-fnt3.datatable-cell.text-right.class-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='result']/tbody/tr/td[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38b745a4-b01f-4a9b-85ae-6782096a3cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pri-fnt3 datatable-cell text-right class-9</value>
      <webElementGuid>0da5b8cd-60a7-4217-99e6-24afdfc917e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>7547ea63-8c72-43c6-904d-2831b73fbfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Quantity Available To Promise</value>
      <webElementGuid>c91b8b9c-5aad-46bb-aa98-4d68a74f1c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>96.000000</value>
      <webElementGuid>3f0863b2-8deb-4603-871e-800b4e59374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result&quot;)/tbody[1]/tr[1]/td[@class=&quot;pri-fnt3 datatable-cell text-right class-9&quot;]</value>
      <webElementGuid>c771fa95-fc2c-47f3-84fe-f3477f073d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='result']/tbody/tr/td[12]</value>
      <webElementGuid>2e300342-1912-4a0d-944f-db19e57370b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::td[8]</value>
      <webElementGuid>09cd38a4-706d-4a17-a41f-49d2572f9ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COCONUT SHAMPOO D'])[1]/following::td[9]</value>
      <webElementGuid>97860513-e847-4bbb-9149-7f7ace121ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::td[3]</value>
      <webElementGuid>56ca937b-82aa-4a12-b561-ab2b00ab8d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE:'])[1]/preceding::td[3]</value>
      <webElementGuid>02d2643b-90f7-4c80-a5c8-6d694fdad990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='96.000000']/parent::*</value>
      <webElementGuid>f2ec1058-4319-483f-a44c-1561a2b31271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]</value>
      <webElementGuid>2057b4b2-3355-4dc2-ac97-60353906c63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '96.000000' or . = '96.000000')]</value>
      <webElementGuid>a43505ea-343b-4c20-b74b-88267baf8bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
