<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Brand</name>
   <tag></tag>
   <elementGuidId>cbe30b89-f81f-4d71-af1a-c8df25f09169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primary_login_page']/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'brand_name_display']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brand_name_display</value>
      <webElementGuid>d48344be-5697-405d-a66e-430809fc60f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
