<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_reveal_password_icon</name>
   <tag></tag>
   <elementGuidId>d0ccf1e2-87d5-4f01-9f33-414b2d13efdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='reveal_password_icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reveal_password_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1bce2705-ea52-46a1-ad0c-13b0f6904f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reveal_password_icon</value>
      <webElementGuid>0d22709d-0e3c-4daf-865f-6c97c4880ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye dis-fnt2</value>
      <webElementGuid>cbd8cbd4-0090-4610-9551-acceb33e9185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reveal_password_icon&quot;)</value>
      <webElementGuid>9d7f24d8-21e3-4efb-a5a6-0bc4ccfcd584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='reveal_password_icon']</value>
      <webElementGuid>0863443a-b39a-4b61-a329-67c6624d23ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='reveal_password']/i</value>
      <webElementGuid>b41ca855-ffe0-4497-9d2a-c48b0be9ebc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>f9636bfe-ba5d-4979-a910-1304a78dadb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'reveal_password_icon']</value>
      <webElementGuid>a73d9cb1-b022-4503-8ee8-5e4f44f4299a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
